### ISSUE TITLE
Potential other comparisons?

### ISSUE THREAD

**Issue by npch** [jasontclark/chaoss-product-comparison#2]
Hi @jasontclark - I'm not sure how far outside the core CHAOSS software packages you're looking to go. If you are comparing against other widely used packages / site, you might want to include [OpenHub](https://www.openhub.net/)?

**Comment by jasontclark** [comment]
@npch - Sure. Anything that we can use to assess what communities are using to measure health I think would be fair game.

**Comment by jasontclark** [comment]
Added d67626895749b173386472e4a22a0d60759a7a7f to include OpenHub.
