### ISSUE TITLE
Consider adding Hubble to the product comparison

### ISSUE THREAD

**Issue by filmaj** [jasontclark/chaoss-product-comparison#5]
Project is open and available here: github.com/autodesk/hubble

Demo of the project available here: https://autodesk.github.io/hubble/

Just a thought 💡

**Comment by jasontclark** [comment]
@filmaj, 👍 - Couldn't hurt to add it. You're more than welcome to create a new markdown file that captures this analysis and send it over in a PR. Thanks for the suggestion!
